version: '3.5'
services:
  discovery:
    hostname: discovery
    image: consul:1.6.3
    command: "agent -server -ui -node=server1 -bootstrap-expect=1 -client=0.0.0.0"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - consul-net
  config-server:
    depends_on:
      - discovery
    image: openjdk:8-alpine
    ports:
      - 9001:9001
    volumes:
      - "./business-services/common/target/common-1.0.jar:/app.jar"
    command: "java -jar app.jar"
    networks:
      - consul-net
  movies-service:
    depends_on:
      - config-server
    image: openjdk:8-alpine
    ports:
      - 8081:8081
    volumes:
      - "./business-services/movies-service/target/movies-service-1.0.jar:/app.jar"
    command: "java -jar app.jar"
    networks:
      - consul-net
  media-service:
    depends_on:
      - config-server
    image: openjdk:8-alpine
    ports:
      - 8082:8082
    volumes:
      - "./business-services/media-service/target/media-service-1.0.jar:/app.jar"
    command: "java -jar app.jar"
    networks:
      - consul-net
  gateway:
    depends_on:
      - config-server
    image: openjdk:8-alpine
    ports:
      - 8080:8080
    volumes:
      - "./platform-services/gateway/target/gateway-1.0.jar:/app.jar"
    command: "java -jar app.jar"
    networks:
      - consul-net
networks:
  consul-net:
    driver: bridge
