spring:
  cloud:
    consul:
      port: '8500'
      discovery:
        instance-id: ${spring.application.name}:${server.port}
        instanceZone: zone1
      host: discovery
  application:
    name: media-service
server:
  port: '8082'

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - health
