spring:  
  application:
    name: gateway-service
  cloud:
    consul:
      host: discovery
      port: 8500
      discovery:
        instanceZone: zone1
        register: false
        registerHealthCheck: false
        tags: zone=zone1
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/media/movie/**
          filters:
            - RewritePath=/media/movie/(?<path>.*), /$\{path}
        - id: movies-service
          uri: lb://movies-service
          predicates:
            - Path=/movies/**
          filters:
            - RewritePath=/movies/(?<path>.*), /$\{path}


logging.level.com.netflix: DEBUG
    
management:
  security:
    enabled: false